#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
ENV_EXAMPLE="${SCRIPT_DIR}/.env.example"
MCP_EXAMPLE="${SCRIPT_DIR}/.mcp.json.example"
MCP_FILE="${SCRIPT_DIR}/.mcp.json"

echo "=== Swarm Orchestrator Setup ==="
echo ""

# ── Helper ────────────────────────────────────────────────────────────
prompt_var() {
    local var_name="$1" description="$2" default="$3" value
    if [[ -n "$default" ]]; then
        read -rp "  ${description} [${default}]: " value
        value="${value:-$default}"
    else
        read -rp "  ${description}: " value
    fi
    echo "${var_name}=${value}" >> "${ENV_FILE}"
    # export so later prompts can reference earlier answers
    export "${var_name}=${value}"
}

# ── .env ──────────────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
    read -rp ".env already exists. Overwrite? [y/N]: " overwrite
    if [[ "$overwrite" != [yY]* ]]; then
        echo "Keeping existing .env"
        echo ""
    else
        rm "$ENV_FILE"
    fi
fi

if [[ ! -f "$ENV_FILE" ]]; then
    echo "Creating .env — press Enter to accept defaults in [brackets]."
    echo ""

    echo "# Generated by setup.sh on $(date -Iseconds)" > "${ENV_FILE}"
    echo "" >> "${ENV_FILE}"

    echo "── Swarm Cluster ──"
    prompt_var "SWARM_MANAGER_SSH" "SSH target for manager node (user@host)" ""

    echo ""
    echo "── Docker Registry ──"
    prompt_var "REGISTRY_HOST" "Private registry address (ip:port)" ""

    echo ""
    echo "── Application ──"
    prompt_var "APP_PORT" "Orchestrator port" "8080"

    echo ""
    echo "── Host Paths (on manager node) ──"
    prompt_var "PROJECTS_HOST_PATH" "Projects dir to mount into container" "/home/${USER}/projects"

    echo "" >> "${ENV_FILE}"
    echo "# Backend (pydantic-settings)" >> "${ENV_FILE}"
    echo "DOCKER_HOST=unix:///var/run/docker.sock" >> "${ENV_FILE}"
    echo "REGISTRY_URL=http://${REGISTRY_HOST}" >> "${ENV_FILE}"
    echo "DATABASE_PATH=./data/swarm_orchestrator.db" >> "${ENV_FILE}"
    echo "DEFINITIONS_DIR=./definitions" >> "${ENV_FILE}"
    echo "PROJECTS_DIR=/projects" >> "${ENV_FILE}"
    echo "HEALTH_CHECK_INTERVAL=30" >> "${ENV_FILE}"
    echo "HOST=0.0.0.0" >> "${ENV_FILE}"
    echo "PORT=${APP_PORT}" >> "${ENV_FILE}"

    echo "" >> "${ENV_FILE}"
    echo "# MCP integrations (optional)" >> "${ENV_FILE}"
    echo "OLLAMA_HOST=http://localhost:11434" >> "${ENV_FILE}"
    echo "OPENWEBUI_URL=http://localhost:3000" >> "${ENV_FILE}"
    echo "OPENWEBUI_API_KEY=" >> "${ENV_FILE}"

    echo ""
    echo ".env created."
fi

# ── .mcp.json ─────────────────────────────────────────────────────────
if [[ ! -f "$MCP_FILE" ]] && [[ -f "$MCP_EXAMPLE" ]]; then
    echo ""
    read -rp "Create .mcp.json from example? [Y/n]: " create_mcp
    if [[ "$create_mcp" != [nN]* ]]; then
        cp "$MCP_EXAMPLE" "$MCP_FILE"
        echo ".mcp.json created. Edit it to match your local paths."
    fi
fi

# ── definitions/ ──────────────────────────────────────────────────────
mkdir -p "${SCRIPT_DIR}/definitions/examples"

# ── Validate Docker ───────────────────────────────────────────────────
echo ""
echo "── Checking Docker connectivity ──"
if docker info > /dev/null 2>&1; then
    echo "  Docker is reachable."
    if docker info 2>/dev/null | grep -q "Swarm: active"; then
        echo "  Swarm mode is active."
    else
        echo "  WARNING: Swarm mode is not active. Run 'docker swarm init' on your manager."
    fi
else
    echo "  WARNING: Cannot connect to Docker. Ensure Docker is running."
fi

echo ""
echo "Setup complete! Next steps:"
echo "  1. Review .env and adjust values as needed"
echo "  2. Add service definitions in definitions/ (see definitions/examples/)"
echo "  3. Run ./deploy.sh build to build and push the image"
echo "  4. Run ./deploy.sh deploy to deploy the stack"
